const tags = [
  "Frontend Development",
  "Backend Development",
  "Mobile App Development",
  "UI/UX Design",
  "State Management",
  "Automated Testing",
  // "Security Measures",
  // "Microservices Architecture",
  "Deployment Strategies",
  "Performance Optimization",
  "E-commerce Solutions",
  "Data Visualization",
  "Responsive Design",
  // "Cross-platform Development",
  "Data Analysis",
  "SEO Optimization",
  "Inclusive Design",
  "Authentication Systems",
  "Real-time Validation",
  "Accessibility Standards",
  "Testing Practices",
  "Progressive Web App",
  "Personalization Features",
  "Database Management",
  "API Development",
  "API Documentation",
  "Component Documentation",
];

//  const PROJECTS = [
//   {
//     id: 8,
//     summary:
//       "This React Native app is an interactive clone of the Pinterest UI, developed with the educational goal of acquiring practical skills in mobile app development.",
//     techs: {
//       language: ["TypeScript"],
//       frontend: [
//         "React Native",
//         "Expo",
//         "React Native Reanimated",
//         "Redux Toolkit",
//       ],
//     },
//     features: [
//       "Robust state management architecture using Redux Toolkit for efficient data handling and smooth interactions throughout the app.",
//       "Design and development of custom components to replicate the Pinterest aesthetic.",
//       "Enhanced animations and interactions using React Native Reanimated",
//       "Enhanced user experience with Loading Skeletons for smoother content loading.",
//       "Enablement of 'Share Photo' feature to promote content sharing and user interaction.",
//       "Incorporation of 'Download Photo' functionality for convenient access to saved content.",
//     ],
//   },
//   {
//     id: 7,
//     summary:
//       "A demand-driven supermarket product search engine and price tracker. It allows users to find products in multiple supermarkets and track price variations of their favorite products.",
//     techs: {
//       language: ["TypeScript"],
//       frontend: [
//         "React",
//         "Redux Toolkit",
//         "React Router Dom",
//         "Ant Design",
//         "D3.js",
//       ],
//       backend: [
//         "Node.js",
//         "Express",
//         "Firebase",
//         "Puppeteer",
//         "Redis",
//         "Supertest",
//         "Swagger",
//       ],
//       hosting: ["Vercel", "Heroku"],
//     },
//     features: [
//       "User empowerment through easy cross-supermarket product search.",
//       "Dynamic price tracker implementation for monitoring and analyzing product price variations.",
//     ],
//   },
//   {
//     id: 6,
//     summary:
//       "SEO-optimized, serverless blog with full customization capabilities. Focused on enhancing user engagement, simplifying content management, and integrating thoughtful accessibility features for an inclusive online experience.",
//     techs: {
//       language: ["TypeScript"],
//       frontend: ["Next.js", "React Hook Form", "React Query", "CSS"],
//       backend: ["Contentful CMS", "Auth0", "Cusdis", "Email.js"],
//       testing: ["React Testing Library", "Jest", "Cypress"],
//       hosting: ["Vercel"],
//     },
//     features: [
//       "Secure User Authentication for a personalized and protected user experience.",
//       "Unit and Integration test setups ensuring codebase reliability and robust functionality.",
//       "Accessibility focus with thoughtfully designed and documented components.",
//       "Lazy loading and loading indicators for an enhanced and responsive user interface.",
//       "Functionality to set random posts, popular posts, feature posts, and integrate social channels.",
//       "Capabilities to publish, unpublish, and delete posts and new pages for content management flexibility.",
//       "Post sharing and commenting features to promote user engagement and interaction.",
//       "Contact form with real-time validation for seamless user input and communication.",
//     ],
//   },
//   {
//     id: 5,
//     summary:
//       "A secure and high-performance login page for ORTEX, incorporating automated unit tests, integration tests, and performance audits to ensure robust functionality and reliability.",
//     techs: {
//       language: ["TypeScript"],
//       frontend: ["Next.js", "CSS", "Storybook"],
//       backend: ["Tradingeconomics API"],
//       testing: [
//         "React Testing Library",
//         "Jest",
//         "Cypress",
//         "Github Actions",
//         "lighthouse CL",
//         "WAVE",
//         "W3C Validators",
//       ],
//       hosting: ["Vercel"],
//     },
//     features: [
//       "Lighthouse pipeline for continuous performance monitoring and enhancement.",
//       "Dedicated integration tests pipeline validating seamless interactions across components.",
//       "Comprehensive unit tests pipeline ensuring reliable codebase integrity and functionality.",
//       "Customizable form with built-in validation for a user-friendly and error-free experience.",
//       "Documentation and accessibility improvements promoting code transparency and collaboration.",
//       "Integration of push notifications for real-time updates and enhanced user engagement.",
//       "Incorporation of loading indicators for a smooth and responsive interface.",
//       "Implementation of a Websocket connection for efficient and real-time communication with tradingeconomics API.",
//     ],
//   },
//   {
//     id: 4,
//     summary:
//       "A flexible platform to simplify hotel and booking management. It offers customizable hotel profiles and guest data displays, providing operational efficiency and personalized experiences for various businesses, including those with multiple hotels and administrators.",
//     techs: {
//       language: ["TypeScript"],
//       frontend: [
//         "Next.js",
//         "Apollo GraphQL Client",
//         "Material-UI",
//         "React Hook Form",
//       ],
//       backend: [
//         "Apollo GraphQL Server",
//         "PostgreSQL",
//         "Nexus",
//         "Prisma",
//         "Cloudinary",
//         "Json JWT",
//       ],
//       hosting: ["Vercel"],
//     },
//     features: [
//       "Efficient search functionality by hotel name or location with real-time suggestions for a seamless user experience.",
//       "Advanced hotel filtering options for tailored search results.",
//       "Interactive and customizable hotel Testimonials and reviews section for user-driven content.",
//       "Easy navigation and booking process with an intuitive user interface.",
//       "Multi-level authentication and authorization processes for secure user and admin interactions.",
//       "User-friendly forms with validation and error handling for smooth data submission.",
//       "Efficient GraphQL queries for optimized data fetching and updating.",
//       "Secure and encrypted user authentication process with Json Web Tokens.",
//       "Responsive design for accessibility across various devices.",
//     ],
//   },
//   {
//     id: 3,
//     summary:
//       "Application created to empower individuals to discover, personalize, and track their food choices through a user-friendly web application, promoting informed decision-making and sustainable healthy eating habits.",
//     techs: {
//       language: ["JavaScript"],
//       frontend: [
//         "Next.js",
//         "Next Auth",
//         "Next PWA",
//         "Tailwind",
//         "React Hook Form",
//       ],
//       backend: ["PostgreSQL", "Prisma"],
//       testing: ["React Testing Library", "Jest", "Cypress"],
//       hosting: ["Vercel"],
//     },
//     features: [
//       "Crafted as a Progressive Web App for seamless user experience across devices.",
//       "Implementation of robust Unit Tests for reliable codebase integrity.",
//       "Comprehensive End-to-End tests ensuring end-user functionalities meet high standards.",
//       "Intuitive display of collection tags on recipes, enhancing user organization.",
//       "Thoroughly tested ARM, macros, and meal size calculators for accuracy and reliability.",
//       "Dedicated Recipe Details page for in-depth exploration of culinary creations.",
//       "User-friendly pages for managing and showcasing personalized recipe collections.",
//       "Empowering users with the ability to create, rename, and delete collections effortlessly.",
//       "Efficient management of recipes, including storage, movement, and deletion functionalities.",
//       "Real-time form validation for an enhanced and error-free user input experience.",
//       "Seamless integration of loading indicators to provide users with a smooth interaction.",
//       "Ensured security through protected routes, safeguarding sensitive areas of the application.",
//       "Dynamic content adaptation with conditional rendering for a personalized user journey.",
//       "Streamlined user onboarding with social sign-in capabilities.",
//     ],
//   },
//   {
//     id: 2,
//     summary:
//       "An inclusive solution designed to assist restaurants in advertising and managing their menu effectively. The application provides real-time monitoring and updates on order status, ensuring seamless operations for both restaurant owners and customers.",
//     techs: {
//       language: ["JavaScript"],
//       frontend: [
//         "React",
//         "Context Api",
//         "React Router Dom",
//         "Styled Components",
//         "React Hook Form",
//         "Socket.io Client",
//         "Swiper",
//       ],
//       backend: [
//         "Node.js",
//         "Express",
//         "MongodDB",
//         "Mongoose",
//         "Cloudinary",
//         "OAuth 2.0",
//         "Nodemailer",
//         "Socket.io",
//         "Json JWT",
//       ],
//       hosting: ["Heroku"],
//     },
//     features: [
//       "Robust authentication system with seamless forgot password support for enhanced security.",
//       "Email account validation through email, ensuring valid user registrations.",
//       "Fully functional newsletter and contact form, fostering effective communication.",
//       "Comprehensive form fields validation to guarantee accurate and error-free data input.",
//       "Multimedia storage capabilities for a rich and engaging user experience.",
//       "Real-time notifications for new orders and updates, keeping users informed and engaged.",
//       "Implementation of unit tests for code reliability, ensuring a stable and resilient system.",
//       "Lazy loading components and code splitting for optimized performance and faster load times.",
//       "Loading skeletons for smoother product and order loading, enhancing user experience.",
//       "Server and client-side pagination for efficient data handling and improved scalability.",
//       "Enhanced products and orders section with sorter, filter, and search bar functionalities for easy navigation.",
//       "Support for search parameters in the URL, offering a seamless and intuitive search experience.",
//       "Custom auto-played sliders with dot indicators and controls for dynamic content presentation.",
//       "Latest product's carousel for captivating and dynamic showcasing of new arrivals.",
//       "Access control with Public and Private routes based on user roles, ensuring data security.",
//       "Functional contact section with thorough form validation for accurate user inquiries.",
//       "Loading modals and indicators for a seamless user experience during data processing.",
//       "Cart management features, including adding, selecting quantity, and removing products for effortless shopping.",
//       "Editable user profiles for a personalized and user-centric experience.",
//       "Order history and status tracking, providing users with transparency and control.",
//       "Order cancellation option available before acceptance by the admin, enhancing user flexibility.",
//       "Comprehensive product management: add, edit, delete, or hide products for efficient inventory control.",
//       "Category management features: add, rename, and eliminate categories along with their associated products.",
//       "Update order status functionality for streamlined and efficient order management.",
//     ],
//   },
//   {
//     id: 1,
//     summary:
//       "A modern and interactive web portfolio meticulously crafted with vanilla JavaScript (no external libraries used) to elevate the experience of showcasing photographic services.",
//     techs: {
//       language: ["JavaScript"],
//       frontend: ["CSS", "HTML"],
//       testing: ["Lighthouse", "WAVE", "W3C Validators"],
//       hosting: ["Vercel"],
//     },
//     features: [
//       "Elegantly structured with modularized JavaScript code for maintainability and scalability.",
//       "Visually stunning projects gallery featuring hover effects and an animated zoom modal for a captivating user experience.",
//       "Engaging on-scroll animations to enhance the overall dynamism and interactivity of the website.",
//       "Dynamic auto-played slider showcasing client testimonials to build trust and credibility.",
//       "Skill progress bars providing a visual representation of expertise, promoting transparency.",
//       "Track and display achievements with interactive counters, highlighting project milestones.",
//       "User-friendly drop-down FAQ list for quick access to essential information.",
//       "Sleek and animated menu navigation for an aesthetically pleasing and modern design.",
//       "Robust form validation ensuring data accuracy and a smooth user interaction.",
//       "Convenient scroll-to-top button with smooth transitions for effortless navigation.",
//     ],
//   },
// ];
const keywords = [
  {
    id: 8,
    keywords: {
      techs: [
        "TypeScript",
        "React Native",
        "Expo",
        "React Native Reanimated",
        "Redux Toolkit",
      ],
      topics: [
        "pinterest clone",
        "mobile app development",
        "ui design",
        "photo sharing",
        "social media",
      ],
      features: [
        "robust state management",
        "custom components",
        "enhanced animations",
        "smoother content loading",
        "share photo",
        "download photo",
      ],
      others: ["educational project", "practical skills", "user experience"],
    },
  },
  {
    id: 7,
    keywords: {
      techs: [
        "TypeScript",
        "React",
        "Redux Toolkit",
        "React Router Dom",
        "Ant Design",
        "D3.js",
        "Node.js",
        "Express",
        "Firebase",
        "Puppeteer",
        "Redis",
        "Supertest",
        "Swagger",
        "Vercel",
        "Heroku",
      ],
      topics: [
        "product search",
        "price comparison",
        "supermarket",
        "shopping",
        "web scraping",
        "web scraper app",
        "demand driven",
        "price tracking",
      ],
      features: [
        "cross supermarket search",
        "price tracking",
        "product comparison",
        "data visualization",
      ],
      others: [
        "web application",
        "e-commerce",
        "personal finance",
        "data analysis",
      ],
    },
  },
  {
    id: 6,
    keywords: {
      techs: [
        "TypeScript",
        "Next.js",
        "React Hook Form",
        "React Query",
        "CSS",
        "Contentful CMS",
        "Auth0",
        "Cusdis",
        "Email.js",
        "React Testing Library",
        "Jest",
        "Cypress",
        "Vercel",
      ],
      topics: [
        "jamstack blog",
        "tech blog",
        "seo optimization",
        "user engagement",
        "content management",
        "accessibility",
        "inclusive design",
      ],
      features: [
        "secure user authentication",
        "unit and integration testing",
        "accessibility focus",
        "lazy loading",
        "dynamic post settings",
        "content management flexibility",
        "post sharing and commenting",
        "contact form with validation",
      ],
      others: [
        "serverless",
        "customization",
        "real-time validation",
        "responsive ui",
      ],
    },
  },
  {
    id: 5,
    keywords: {
      techs: [
        "TypeScript",
        "Next.js",
        "CSS",
        "Storybook",
        "Tradingeconomics API",
        "React Testing Library",
        "Jest",
        "Cypress",
        "lighthouse CL",
        "WAVE",
        "Github Actions",
        "W3C Validators",
        "Vercel",
      ],
      topics: [
        "login page",
        "github actions",
        "performance optimization",
        "automated testing",
        "code quality",
        "user experience",
        "real-time updates",
        "websockets",
      ],
      features: [
        "lighthouse pipeline",
        "integration tests pipeline",
        "unit tests pipeline",
        "customizable form with validation",
        "documentation and accessibility improvements",
        "push notifications",
        "loading indicators",
        "websocket connection",
      ],
      others: [
        "secure",
        "high performance",
        "codebase integrity",
        "error free",
        "responsive",
      ],
    },
  },
  {
    id: 4,
    keywords: {
      techs: [
        "TypeScript",
        "Next.js",
        "Apollo GraphQL Client",
        "Material-IU",
        "React Hook Form",
        "Apollo GraphQL Server",
        "PostgreSQL",
        "Nexus",
        "Prisma",
        "Cloudinary",
        "Json JWT",
        "Vercel",
      ],
      topics: [
        "hotel booking app",
        "graphql",
        "booking management",
        "hotel management",
        "search and filtering",
        "user experience",
        "reservation system",
        "authentication",
        "multiple hotels",
        "customization",
        "data management",
        "calendar",
        "file storage",
      ],
      features: [
        "real time search suggestions",
        "advanced hotel filtering",
        "user friendly pagination",
        "push notifications",
        "streamlined booking process",
        "robust authentication",
        "support for multiple hotels and administrators",
        "customizable hotel and room thumbnails",
        "editing capabilities",
        "room categorization and quota assignment",
        "visual booking management",
        "external reservation integration",
        "guest management",
        "reservation calendar",
        "folder system and multimedia storage",
      ],
      others: [],
    },
  },
  {
    id: 3,
    keywords: {
      techs: [
        "JavaScript",
        "Next.js",
        "Next Auth",
        "Next PWA",
        "Tailwind",
        "React Hook Form",
        "PostgreSQL",
        "Prisma",
        "React Testing Library",
        "Jest",
        "Cypress",
        "Vercel",
      ],
      topics: [
        "fitness app",
        "recipe app",
        "progressive web app",
        "nutrition tracking",
        "healthy eating",
        "recipe discovery",
        "personalized collections",
        "calorie tracking",
        "macro tracking",
        "user experience",
        "personalization",
        "health and wellness",
      ],
      features: [
        "pwa functionality",
        "unit tests",
        "end-to-end tests",
        "collection tags",
        "calculators",
        "recipe details page",
        "collection management",
        "recipe management",
        "real-time form validation",
        "loading indicators",
        "protected routes",
        "conditional rendering",
        "social sign-in",
      ],
      others: ["image-rich", "user-friendly interface", "smooth interactions"],
    },
  },
  {
    id: 2,
    keywords: {
      techs: [
        "JavaScript",
        "React",
        "Context Api",
        "React Router Dom",
        "Styled Components",
        "React Hook Form",
        "Socket.io Client",
        "Swiper",
        "Node.js",
        "Express",
        "MongodDB",
        "Mongoose",
        "Cloudinary",
        "OAuth 2.0",
        "Nodemailer",
        "Socket.io",
        "Json JWT",
        "Heroku",
      ],
      topics: [
        "delivery app",
        "restaurant management",
        "order tracking",
        "real time updates",
        "user friendly",
        "secure authentication",
        "email validation",
        "newsletter",
        "contact form",
        "unit tests",
        "lazy loading",
        "server and client-side pagination",
        "filtering and sorting",
        "url search parameter support",
        "dynamic content",
        "user roles and access control",
        "editable user profiles",
        "cart management",
        "order history",
        "order cancellation",
        "product management",
        "category management",
      ],
      features: [
        "robust authentication with forgot password",
        "email account validation",
        "functional newsletter and contact form",
        "comprehensive form validation",
        "multimedia storage",
        "real-time notifications",
        "unit tests",
        "lazy loading and code splitting",
        "loading skeletons",
        "server and client-side pagination",
        "enhanced products and orders section",
        "url search parameter support",
        "custom auto-played sliders",
        "latest product carousel",
        "access control with public and private routes",
        "functional contact section with form validation",
        "loading modals and indicators",
        "cart management features",
        "editable user profiles",
        "order history and status tracking",
        "order cancellation before admin acceptance",
        "comprehensive product management",
        "category management functionalities",
        "update order status functionality",
      ],
      others: [],
    },
  },
  {
    id: 1,
    keywords: {
      techs: [
        "JavaScript",
        "CSS",
        "HTML",
        "lighthouse CL",
        "WAVE",
        "W3C Validators",
        "Vercel",
      ],
      topics: [
        "photographer portfolio",
        "web portfolio",
        "vanilla javascript",
        "interactive website",
        "photography website",
        "no external libraries",
      ],
      features: [
        "modular javascript",
        "project gallery",
        "hover effects",
        "zoom modal",
        "on scroll animations",
        "client testimonials slider",
        "skill progress bars",
        "interactive counters",
        "dropdown faq",
        "animated menu navigation",
        "form validation",
        "scroll to top button",
      ],
      others: ["modern design"],
    },
  },
];

const projects = [
  {
    id: 8,
    title: "Pinterest Clone",
    subtitle: "React Native App",
    tags: [
      "TypeScript",
      "React Native",
      "Expo",
      "React Native Reanimated",
      "Redux Toolkit",
      "Mobile App Development",
      "Frontend Development",
      "State Management",
      "UI/UX Design",
      "Cross-platform Development",
    ],
  },
  {
    id: 7,
    title: "Smart Buy",
    subtitle: "Web Scraper App",
    tags: [
      "TypeScript",
      "React",
      "Redux Toolkit",
      "React Router Dom",
      "Ant Design",
      "D3.js",
      "Node.js",
      "Express",
      "Firebase",
      "Puppeteer",
      "Redis",
      "Supertest",
      "Swagger",
      "Vercel",
      "Heroku",
      "Frontend Development",
      "Backend Development",
      "Automated Testing",
      "Data Visualization",
      "E-commerce Solutions",
      "API Development",
      "Deployment Strategies",
    ],
  },
  {
    id: 6,
    title: "Tecno Rev",
    subtitle: "JAMstack blog",
    tags: [
      "TypeScript",
      "Next.js",
      "React Hook Form",
      "React Query",
      "CSS",
      "Contentful CMS",
      "Auth0",
      "Cusdis",
      "Email.js",
      "React Testing Library",
      "Jest",
      "Cypress",
      "Vercel",
      "Frontend Development",
      "Backend Development",
      "Automated Testing",
      "UI/UX Design",
      "Accessibility Standards",
      "User Authentication",
      "Inclusive Design",
    ],
  },
  {
    id: 5,
    title: "ORTEX login",
    subtitle: "Github actions pipeline",
    tags: [
      "TypeScript",
      "Next.js",
      "CSS",
      "Storybook",
      "Tradingeconomics API",
      "React Testing Library",
      "Jest",
      "Cypress",
      "lighthouse CL",
      "WAVE",
      "Github Actions",
      "W3C Validators",
      "Vercel",
      "Frontend Development",
      "Backend Development",
      "Automated Testing",
      "Security Measures",
      "Real-time Validation",
      "Performance Optimization",
      "Progressive Web App",
      "API Development",
    ],
  },
  {
    id: 4,
    title: "Hotel Booker",
    subtitle: "Graphql App",
    tags: [
      "TypeScript",
      "Next.js",
      "Apollo GraphQL Client",
      "Material-IU",
      "React Hook Form",
      "Apollo GraphQL Server",
      "PostgreSQL",
      "Nexus",
      "Prisma",
      "Cloudinary",
      "Json JWT",
      "Vercel",
      "Frontend Development",
      "Backend Development",
      "Database Management",
      "UI/UX Design",
      "Authentication Systems",
      "Responsive Design",
    ],
  },
  {
    id: 3,
    title: "wikifit",
    subtitle: "Progressive web App",
    tags: [
      "JavaScript",
      "Next.js",
      "Next Auth",
      "Next PWA",
      "Tailwind",
      "React Hook Form",
      "PostgreSQL",
      "Prisma",
      "React Testing Library",
      "Jest",
      "Cypress",
      "Vercel",
      "Frontend Development",
      "Backend Development",
      "Automated Testing",
      "UI/UX Design",
      "Cross-platform Development",
      "Progressive Web App",
      "Data Analysis",
      "User Authentication",
      "End-to-end Testing",
    ],
  },
  {
    id: 2,
    title: "delivery app",
    subtitle: "Socket.IO MERN stack App",
    tags: [
      "JavaScript",
      "React",
      "Context Api",
      "React Router Dom",
      "Styled Components",
      "React Hook Form",
      "Socket.io Client",
      "Swiper",
      "Node.js",
      "Express",
      "MongodDB",
      "Mongoose",
      "Cloudinary",
      "OAuth 2.0",
      "Nodemailer",
      "Socket.io",
      "Json JWT",
      "Heroku",
      "Frontend Development",
      "Backend Development",
      "Real-time Validation",
      "Performance Optimization",
      "Security Measures",
      "Database Management",
      "API Development",
    ],
  },
  {
    id: 1,
    title: "photographer portfolio",
    subtitle: "interactive vanilla.JS website",
    tags: [
      "JavaScript",
      "CSS",
      "HTML",
      "lighthouse CL",
      "WAVE",
      "W3C Validators",
      "Vercel",
      "Frontend Development",
      "SEO Optimization",
      "UI/UX Design",
      "Responsive Design",
    ],
  },
];
const projectsWithExcludedTags = projects.map((proj) => ({
  ...proj,
  noTags: tags.filter((tag) => !proj.tags.includes(tag)),
}));
console.log(projectsWithExcludedTags);
